#
# ███████╗███████╗███████╗██╗  ██╗     ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
# ██╔════╝██╔════╝██╔════╝██║  ██║    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
# ███████╗█████╗  ███████╗███████║    ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ╚════██║██╔══╝  ╚════██║██╔══██║    ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
# ███████║███████╗███████║██║  ██║    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
# ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 
#
# Smart session manager for the terminal
# https://github.com/joshmedeski/sesh

strict_mode = false

# default

[default_session]
startup_command = "nvim -c 'lua require(\"snacks\").picker.smart({ filter = { cwd = true } })'"
preview_command = "eza --all --git --icons --color=always {}"

sort_order = [
    "pulstar",
    "downloads",
    "home",
    "repos",
    "tmux config"
]

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "home"
path = "/Users/pnl0u32w/"
startup_command = "ls"

[[session]]
name = "pulstar"
path = "~/pulstar"
startup_command = "nvim -c 'lua require(\"snacks\").picker.smart({ filter = { cwd = true } })'"

[[session]]
name = "repos"
path = "/Users/pnl0u32w/repos"
startup_command = "ls"

[[session]]
name = "tmux config"
path = "~/pulstar/roles/tmux/files"
startup_command = "nvim -p tmux.conf sesh.toml"
