customCommands:
  - key: "E"
    description: "Add empty commit"
    context: "commits"
    command: 'git commit --allow-empty -m "chore: empty commit to trigger automation"'
    loadingText: "Committing empty commit..."
promptToReturnFromSubprocess: false
