"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$character\
"""

palette = "rose_pine"

# https://rosepinetheme.com/palette/ingredients/#rose-pine
[palettes.rose_pine]
base    = "#191724"
surface = "#1f1d2e"
overlay = "#26233a"
muted   = "#6e6a86"
subtle  = "#908caa"
text    = "#e0def4"
love    = "#eb6f92"
gold    = "#f6c177"
rose    = "#ebbcba"
pine    = "#31748f"
foam    = "#9ccfd8"
iris    = "#c4a7e7"
hl_low  = "#21202e"
hl_mid  = "#403d52"
hl_high = "#524f67"

[character]
disabled = false
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[directory]
truncation_length = 8

[git_commit]
disabled = false
tag_symbol = " tag "

[git_status]
renamed = "r"
deleted = "x"
ahead = '>${count}'
diverged = '<>${ahead_count}<${behind_count}'
behind = '<${count}'

[line_break]
disabled = false

[git_branch]
symbol = "branch:"
